# Generated by Django 6.0.3 on 2026-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_url', models.URLField(max_length=2000, verbose_name='Scanned URL')),
                ('scan_type', models.CharField(choices=[('QR', 'QR Code'), ('URL', 'Manual URL')], max_length=10, verbose_name='Scan Type')),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('HIGH RISK', 'High Risk')], max_length=20, verbose_name='Risk Level')),
                ('risk_score', models.IntegerField(verbose_name='Risk Score (0–100)')),
                ('scan_date', models.DateTimeField(auto_now_add=True, verbose_name='Scan Date')),
            ],
            options={
                'verbose_name': 'Scan Result',
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-scan_date'],
            },
        ),
    ]
